// Master Sector-to-Courses mapping provided by RSLDC Catalog
export interface SectorCourseItem {
  courseName: string;
  defaultDurationHours: number;
}

export const SECTOR_COURSES_MAP: Record<string, SectorCourseItem[]> = {
  "Aerospace and Aviation": [
    { courseName: "Airline Customer Service Executive", defaultDurationHours: 400 },
    { courseName: "Drone Operator - Multi Rotor", defaultDurationHours: 490 },
  ],
  "Agriculture": [
    { courseName: "Agricultural Field Assistant", defaultDurationHours: 490 },
    { courseName: "Agricultural Machinery Operator", defaultDurationHours: 490 },
    { courseName: "Agricultural Sales Representative", defaultDurationHours: 490 },
    { courseName: "Agriculture Extension Service Provider", defaultDurationHours: 460 },
    { courseName: "Assistant Gardener", defaultDurationHours: 370 },
    { courseName: "Bee Keeper", defaultDurationHours: 430 },
    { courseName: "Combine Harvester Machine Operator", defaultDurationHours: 490 },
    { courseName: "Custom Hiring Centre Operator", defaultDurationHours: 490 },
    { courseName: "Dairy Farmer/Entrepreneur", defaultDurationHours: 490 },
    { courseName: "Design and construct Vertical Garden", defaultDurationHours: 137 },
    { courseName: "Farm Mechanic", defaultDurationHours: 490 },
    { courseName: "Farm Supervisor", defaultDurationHours: 490 },
    { courseName: "Fisheries Worker", defaultDurationHours: 430 },
    { courseName: "Floriculture Technician", defaultDurationHours: 430 },
    { courseName: "Floriculturist", defaultDurationHours: 430 },
    { courseName: "Florist", defaultDurationHours: 370 },
    { courseName: "Goat Farmer", defaultDurationHours: 490 },
    { courseName: "Greenhouse Installer", defaultDurationHours: 490 },
    { courseName: "Greenhouse Operator", defaultDurationHours: 370 },
    { courseName: "Herb Grower", defaultDurationHours: 310 },
    { courseName: "Hydroponics Technician", defaultDurationHours: 370 },
    { courseName: "Irrigation Service Technician", defaultDurationHours: 490 },
    { courseName: "Kisan Drone Operator", defaultDurationHours: 369 },
    { courseName: "Master Gardener", defaultDurationHours: 490 },
    { courseName: "Medicinal and Aromatic Plants Grower", defaultDurationHours: 460 },
    { courseName: "Micro-Irrigation Technician", defaultDurationHours: 490 },
    { courseName: "Mushroom Grower", defaultDurationHours: 430 },
    { courseName: "Nursery Worker", defaultDurationHours: 430 },
    { courseName: "Organic Grower", defaultDurationHours: 490 },
    { courseName: "Poultry Farmer", defaultDurationHours: 490 },
    { courseName: "Repair & Maintenance of solar powered farm equipment/ machinery", defaultDurationHours: 137 },
    { courseName: "Seed Bank Management", defaultDurationHours: 137 },
    { courseName: "Seed Processing Worker", defaultDurationHours: 490 },
    { courseName: "Sheep Farmer", defaultDurationHours: 490 },
    { courseName: "Soil Testing Laboratory Assistant", defaultDurationHours: 490 },
    { courseName: "Spice Crop Cultivator", defaultDurationHours: 430 },
    { courseName: "Tractor Operator", defaultDurationHours: 490 },
    { courseName: "Vermicompost Producer", defaultDurationHours: 430 },
  ],
  "Apparel": [
    { courseName: "Assistant Fashion Designer", defaultDurationHours: 550 },
    { courseName: "Cutting Machine Operator", defaultDurationHours: 550 },
    { courseName: "Fashion Designer", defaultDurationHours: 550 },
    { courseName: "Garment Checker", defaultDurationHours: 490 },
    { courseName: "Hand Embroiderer", defaultDurationHours: 490 },
    { courseName: "Production Supervisor", defaultDurationHours: 550 },
    { courseName: "Quality Checker - Apparel", defaultDurationHours: 550 },
    { courseName: "Self Employed Tailor", defaultDurationHours: 550 },
    { courseName: "Sewing Machine Operator", defaultDurationHours: 550 },
    { courseName: "Sewing Machine Operator - Knits", defaultDurationHours: 550 },
    { courseName: "Sewing Machine Operator - Woven", defaultDurationHours: 550 },
  ],
  "Automotive": [
    { courseName: "Automotive Body Repair Technician", defaultDurationHours: 550 },
    { courseName: "Automotive Electrician", defaultDurationHours: 550 },
    { courseName: "Automotive Engine Repair Technician", defaultDurationHours: 550 },
    { courseName: "Automotive Painter", defaultDurationHours: 550 },
    { courseName: "Automotive Sales Consultant", defaultDurationHours: 550 },
    { courseName: "Automotive Service Technician", defaultDurationHours: 550 },
    { courseName: "Automotive Transmission Repair Technician", defaultDurationHours: 550 },
    { courseName: "Electric Vehicle Service Technician", defaultDurationHours: 550 },
    { courseName: "Four Wheeler Service Technician", defaultDurationHours: 550 },
    { courseName: "Service Advisor", defaultDurationHours: 550 },
    { courseName: "Two Wheeler Service Technician", defaultDurationHours: 550 },
    { courseName: "Wheel Alignment Technician", defaultDurationHours: 550 },
  ],
  "BFSI": [
    { courseName: "Accounts Executive", defaultDurationHours: 490 },
    { courseName: "Banking Sales Officer", defaultDurationHours: 550 },
    { courseName: "Insurance Agent", defaultDurationHours: 490 },
    { courseName: "Microfinance Executive", defaultDurationHours: 490 },
  ],
  "Beauty & Wellness": [
    { courseName: "Assistant Beauty Therapist", defaultDurationHours: 490 },
    { courseName: "Beauty Therapist", defaultDurationHours: 550 },
    { courseName: "Hair Stylist", defaultDurationHours: 550 },
    { courseName: "Makeup Artist", defaultDurationHours: 490 },
    { courseName: "Nail Technician", defaultDurationHours: 490 },
    { courseName: "Spa Therapist", defaultDurationHours: 550 },
  ],
  "Capital Goods": [
    { courseName: "CNC Operator", defaultDurationHours: 550 },
    { courseName: "Fitter", defaultDurationHours: 550 },
    { courseName: "Machine Operator", defaultDurationHours: 550 },
  ],
  "Construction": [
    { courseName: "Assistant Electrician", defaultDurationHours: 460 },
    { courseName: "Assistant Shuttering Carpenter", defaultDurationHours: 460 },
    { courseName: "Bar Bender and Steel Fixer", defaultDurationHours: 550 },
    { courseName: "Construction Painter & Decorator", defaultDurationHours: 520 },
    { courseName: "Foreman - Concrete", defaultDurationHours: 670 },
    { courseName: "Helper Construction Painter", defaultDurationHours: 340 },
    { courseName: "Interior Finisher", defaultDurationHours: 940 },
    { courseName: "MEP Technician", defaultDurationHours: 940 },
    { courseName: "Mason Concrete", defaultDurationHours: 490 },
    { courseName: "Mason Tiling", defaultDurationHours: 550 },
    { courseName: "Rural Mason", defaultDurationHours: 849 },
  ],
  "Domestic Workers": [
    { courseName: "Assistant Home Manager", defaultDurationHours: 610 },
    { courseName: "Care Homes Supervisor", defaultDurationHours: 790 },
    { courseName: "Child Caretaker (Non Clinical)", defaultDurationHours: 460 },
    { courseName: "Elderly Caretaker (Non Clinical)", defaultDurationHours: 460 },
    { courseName: "General Housekeeper (Household and Small Establishment)", defaultDurationHours: 400 },
    { courseName: "Housekeeper cum Cook (Household and Small Establishment)", defaultDurationHours: 400 },
    { courseName: "Multi Skill Technician (Household and Small Establishment)", defaultDurationHours: 460 },
  ],
  "Electronics": [
    { courseName: "Assistant Technician DTH Service", defaultDurationHours: 310 },
    { courseName: "Assistant Technician- Air Conditioner", defaultDurationHours: 310 },
    { courseName: "Assistant Technician- CCTV", defaultDurationHours: 310 },
    { courseName: "Assistant Technician- Computer Hardware", defaultDurationHours: 310 },
    { courseName: "Assistant Technician- Home Appliances", defaultDurationHours: 310 },
    { courseName: "CCTV Installation Technician", defaultDurationHours: 700 },
    { courseName: "Customer Care Executive", defaultDurationHours: 700 },
    { courseName: "Customer Service Executive - Electronic Products", defaultDurationHours: 580 },
    { courseName: "DTH Set Top Box Installation & Service Technician", defaultDurationHours: 700 },
    { courseName: "Drone Manufacturing and Assembly Technician", defaultDurationHours: 550 },
    { courseName: "Drone Service Technician", defaultDurationHours: 550 },
    { courseName: "Electrical Technician", defaultDurationHours: 520 },
    { courseName: "Electronic Hardware Design Engineer", defaultDurationHours: 610 },
    { courseName: "Field Technician - Air Conditioner", defaultDurationHours: 550 },
    { courseName: "Field Technician Computing And Peripherals", defaultDurationHours: 610 },
    { courseName: "Field Technician Networking And Storage", defaultDurationHours: 700 },
    { courseName: "Field Technician Networking and Data Storage", defaultDurationHours: 550 },
    { courseName: "Field Technician Other Home Appliances", defaultDurationHours: 700 },
    { courseName: "Field Technician-UPS And Inverter", defaultDurationHours: 700 },
    { courseName: "Fundamentals of Robotronics", defaultDurationHours: 310 },
    { courseName: "HVAC Technician", defaultDurationHours: 700 },
    { courseName: "Internet of Things (IoT) Assistant", defaultDurationHours: 490 },
    { courseName: "Internet of Things (IoT) Developer", defaultDurationHours: 490 },
    { courseName: "LED Light Repair Technician", defaultDurationHours: 550 },
    { courseName: "Mobile Phone Hardware Repair Technician", defaultDurationHours: 700 },
    { courseName: "Multi Skill Technician (Electrical)", defaultDurationHours: 670 },
    { courseName: "Multi Skill Technician - Consumer Durables", defaultDurationHours: 1360 },
    { courseName: "Robotics Automation Lead", defaultDurationHours: 1360 },
    { courseName: "Service Technician - Home Appliances", defaultDurationHours: 700 },
    { courseName: "Service Technician – Home Appliances", defaultDurationHours: 580 },
    { courseName: "Solar LED Technician", defaultDurationHours: 700 },
    { courseName: "Solar Panel Installation Technician", defaultDurationHours: 700 },
    { courseName: "TV Repair Technician", defaultDurationHours: 520 },
    { courseName: "Welding Operator Electronics", defaultDurationHours: 520 },
    { courseName: "Wireman Control Panel Electronics", defaultDurationHours: 520 },
  ],
  "Food Processing": [
    { courseName: "Dairy Products Processor", defaultDurationHours: 910 },
    { courseName: "Fruit Pulp Processing Technician", defaultDurationHours: 490 },
    { courseName: "Jam, Jelly and Ketchup Processing Technician", defaultDurationHours: 400 },
    { courseName: "Multi Skill Technician (Food Processing)", defaultDurationHours: 980 },
    { courseName: "Multi Skill Technician- Fruits & Vegetables", defaultDurationHours: 310 },
    { courseName: "Plant Biscuit Production Specialist", defaultDurationHours: 430 },
    { courseName: "Traditional sweet and savoury product maker", defaultDurationHours: 420 },
  ],
  "Furniture & Fittings": [
    { courseName: "Assistant Interior Designer", defaultDurationHours: 1660 },
    { courseName: "Assistant Project Manager (Interior Design)", defaultDurationHours: 1270 },
    { courseName: "Carpenter", defaultDurationHours: 100 },
  ],
  "Green Jobs": [
    { courseName: "Green Hydrogen Plant Technician", defaultDurationHours: 460 },
    { courseName: "O&M Mechanical Technician-Wind Power Plant", defaultDurationHours: 300 },
    { courseName: "Small Hydro Power Plant Technician-(Jal Urja Mitra)", defaultDurationHours: 370 },
    { courseName: "Solar PV Cell Manufacturing Technician", defaultDurationHours: 340 },
    { courseName: "Solar PV Installer (Suryamitra)", defaultDurationHours: 520 },
    { courseName: "Solar PV Installer - Electrical", defaultDurationHours: 490 },
    { courseName: "Solar Photovoltaic Technician", defaultDurationHours: 430 },
  ],
  "Handicrafts and Carpet": [
    { courseName: "Advanced Program on Traditional Hand Embroidery", defaultDurationHours: 190 },
    { courseName: "Applique Artisan", defaultDurationHours: 520 },
    { courseName: "Assistant Hand Embroider -(Phulkari / Chickankari / Kashmiri / Zari Zardozi / Kantha)", defaultDurationHours: 100 },
    { courseName: "Carpet Weaver", defaultDurationHours: 1200 },
    { courseName: "Namda Craft Artisan", defaultDurationHours: 460 },
    { courseName: "Namda Craft Maker", defaultDurationHours: 550 },
    { courseName: "Potter (Kumhar) including traditional ceramics and terracotta product maker", defaultDurationHours: 139 },
    { courseName: "Traditional Hand Embroiderer", defaultDurationHours: 1420 },
    { courseName: "Traditional Hand Embroiderer- Supervisor", defaultDurationHours: 1270 },
    { courseName: "Traditional Leather Toy maker", defaultDurationHours: 139 },
  ],
  "Healthcare": [
    { courseName: "Ayurveda Dietician", defaultDurationHours: 700 },
    { courseName: "Emergency Care Assistant", defaultDurationHours: 1600 },
    { courseName: "Emergency Medical Technician-Basic", defaultDurationHours: 490 },
    { courseName: "General Duty Assistant", defaultDurationHours: 1000 },
    { courseName: "General Duty Assistant- Advanced", defaultDurationHours: 1000 },
    { courseName: "General Duty Assistant- Advanced(Elective 1: Critical Care Elective 2: Dialysis Elective 3: Peri- natal care Elective 4: Peri- operative care)", defaultDurationHours: 1060 },
    { courseName: "Geriatric Care Assistant", defaultDurationHours: 1570 },
    { courseName: "Geriatric Caregiver (Institutional & Home Care)", defaultDurationHours: 340 },
    { courseName: "Hospital Front Desk Coordinator", defaultDurationHours: 1000 },
    { courseName: "Multiskilled Health Assistant", defaultDurationHours: 610 },
    { courseName: "Telehealth Services Coordinator", defaultDurationHours: 1100 },
  ],
  "Hydrocarbon": [
    { courseName: "Advance Course on Green Hydrogen", defaultDurationHours: 130 },
    { courseName: "Assistant Technician- Production (Oil & Gas)", defaultDurationHours: 900 },
    { courseName: "Fire Safety Technician (Oil & Gas)", defaultDurationHours: 550 },
    { courseName: "LPG Mechanic", defaultDurationHours: 430 },
  ],
  "IT-ITeS": [
    { courseName: "3D Printing Software Developer", defaultDurationHours: 790 },
    { courseName: "AI - Machine Learning Engineer", defaultDurationHours: 580 },
    { courseName: "AR/VR Architect", defaultDurationHours: 760 },
    { courseName: "AR/VR Designer", defaultDurationHours: 610 },
    { courseName: "AR/VR Software Developer", defaultDurationHours: 640 },
    { courseName: "Artificial Intelligence Assistant", defaultDurationHours: 370 },
    { courseName: "Associate - Customer Care (Non-Voice)", defaultDurationHours: 500 },
    { courseName: "Associate Customer care (Voice and Non-Voice)", defaultDurationHours: 490 },
    { courseName: "Blockchain Strategist", defaultDurationHours: 700 },
    { courseName: "Customer Care Executive- Domestic- Voice", defaultDurationHours: 550 },
    { courseName: "Customer Sr. Executive (Voice and Non- Voice)", defaultDurationHours: 430 },
    { courseName: "Cyber Security for Cloud Infrastructure", defaultDurationHours: 220 },
    { courseName: "Cybersecurity", defaultDurationHours: 610 },
    { courseName: "Data Analysis with Python and SQL", defaultDurationHours: 220 },
    { courseName: "Digital Mitra", defaultDurationHours: 340 },
    { courseName: "Domestic Data Entry Operator", defaultDurationHours: 550 },
    { courseName: "Drone Developer (Software)", defaultDurationHours: 610 },
    { courseName: "Drone Software Technician", defaultDurationHours: 430 },
    { courseName: "IT Professional Skills", defaultDurationHours: 370 },
    { courseName: "IoT - Product Manager", defaultDurationHours: 820 },
    { courseName: "IoT - Security Specialist", defaultDurationHours: 670 },
    { courseName: "IoT - Software Analyst", defaultDurationHours: 790 },
    { courseName: "IoT - Solution Architect", defaultDurationHours: 1030 },
    { courseName: "IoT - Test Analyst", defaultDurationHours: 610 },
    { courseName: "Mobile Application Development", defaultDurationHours: 610 },
    { courseName: "Security Operation Centre Analyst", defaultDurationHours: 520 },
    { courseName: "Software Developer-IT Services", defaultDurationHours: 520 },
    { courseName: "Sr. Associate - Desktop Publishing (DTP)", defaultDurationHours: 520 },
    { courseName: "Web Developer", defaultDurationHours: 490 },
  ],
  "Information Technology Sector": [
    { courseName: "Artificial Intelligence Application Developer", defaultDurationHours: 580 },
    { courseName: "Cloud Computing Assistant", defaultDurationHours: 370 },
    { courseName: "Cyber Security Associate", defaultDurationHours: 580 },
    { courseName: "Digital Content Developer", defaultDurationHours: 670 },
  ],
  "Infrastructure Equipment": [
    { courseName: "Concrete Pump Operator", defaultDurationHours: 420 },
    { courseName: "Crawler Crane Operator", defaultDurationHours: 420 },
    { courseName: "Hot Mix Plant Operator", defaultDurationHours: 420 },
    { courseName: "Hydra Crane Operator", defaultDurationHours: 420 },
    { courseName: "Supervisor (Plant & Machinery)", defaultDurationHours: 640 },
    { courseName: "Wheel Loader Operator", defaultDurationHours: 520 },
  ],
  "Iron and Steel": [
    { courseName: "Assistant - Electrician", defaultDurationHours: 520 },
    { courseName: "Gas Tungsten Arc Welding (GTAW)", defaultDurationHours: 676 },
    { courseName: "Metal Fabricator - Iron and Steel", defaultDurationHours: 580 },
    { courseName: "Mobile Equipment Operator (Metal Sector)", defaultDurationHours: 490 },
    { courseName: "Operator - Mobile Equipment", defaultDurationHours: 520 },
  ],
  "Leather": [
    { courseName: "CAD/CAM Operator (Footwear)", defaultDurationHours: 300 },
    { courseName: "Footwear and Fashion Accessories Retail Associate", defaultDurationHours: 100 },
  ],
  "Life Sciences": [
    { courseName: "Assistant- Maintenance (Pharma, Biologics and Medical Device Facility)", defaultDurationHours: 640 },
    { courseName: "Foundation for Pharma Sales and Marketing", defaultDurationHours: 115 },
    { courseName: "Lab Technician-Research and Quality Control", defaultDurationHours: 355 },
    { courseName: "Manufacturing and Packaging Assistant (Pharma, Biologics and Medical Devices)", defaultDurationHours: 430 },
    { courseName: "Retail Chemist Prescription Audit", defaultDurationHours: 130 },
    { courseName: "Secondary & Tertiary Packaging – Assistant (Pharma, Biologics and Medical device)", defaultDurationHours: 370 },
    { courseName: "Supervisor- Maintenance (Pharma, Biologics and Medical Device Facility)", defaultDurationHours: 1030 },
  ],
  "Logistics": [
    { courseName: "Air Cargo Booking Executive", defaultDurationHours: 550 },
    { courseName: "Cargo Booking Clerk", defaultDurationHours: 310 },
    { courseName: "Commercial Vehicle Driver - LMO", defaultDurationHours: 610 },
    { courseName: "Consignment Booking Assistant", defaultDurationHours: 460 },
    { courseName: "Consignment Delivery Executive.", defaultDurationHours: 310 },
    { courseName: "Courier Associate - Operations", defaultDurationHours: 610 },
    { courseName: "Courier Delivery Executive", defaultDurationHours: 460 },
    { courseName: "Courier Executive - Operations", defaultDurationHours: 1000 },
    { courseName: "Courier Manager - Operations", defaultDurationHours: 880 },
    { courseName: "Crane Operator - Port Terminals/CFS/ICD", defaultDurationHours: 520 },
    { courseName: "Documentation Executive", defaultDurationHours: 550 },
    { courseName: "Drone Operator - Warehouse", defaultDurationHours: 670 },
    { courseName: "Inventory Controller", defaultDurationHours: 310 },
    { courseName: "Key Accounts Management Executive - Courier", defaultDurationHours: 610 },
    { courseName: "Loading Supervisor", defaultDurationHours: 460 },
    { courseName: "Multimodal Transport Planner", defaultDurationHours: 730 },
    { courseName: "Port Terminals/CFS/ICD Supervisor", defaultDurationHours: 610 },
    { courseName: "Supply Chain Executive", defaultDurationHours: 670 },
    { courseName: "Supply Chain Supervisor - Agri Commodities", defaultDurationHours: 970 },
    { courseName: "Warehouse Associate", defaultDurationHours: 880 },
    { courseName: "Warehouse Executive", defaultDurationHours: 550 },
    { courseName: "Warehouse Packer", defaultDurationHours: 460 },
    { courseName: "Warehouse Supervisor", defaultDurationHours: 640 },
  ],
  "Management": [
    { courseName: "CCTV Supervisor", defaultDurationHours: 490 },
    { courseName: "Career and Education Counsellor", defaultDurationHours: 670 },
    { courseName: "Firefighter", defaultDurationHours: 700 },
    { courseName: "General Duty Guard cum Watchman", defaultDurationHours: 310 },
    { courseName: "Office Assistant", defaultDurationHours: 430 },
    { courseName: "Office Executive", defaultDurationHours: 490 },
    { courseName: "Personal Security Officer", defaultDurationHours: 520 },
    { courseName: "Receptionist", defaultDurationHours: 400 },
    { courseName: "Security Guard", defaultDurationHours: 430 },
    { courseName: "Security Supervisor", defaultDurationHours: 580 },
  ],
  "Media & Entertainment": [
    { courseName: "3D Animator (TV and Film Making)", defaultDurationHours: 640 },
    { courseName: "3D Printing Operator", defaultDurationHours: 670 },
    { courseName: "AR VR Producer", defaultDurationHours: 940 },
    { courseName: "AR-VR Developer", defaultDurationHours: 1720 },
    { courseName: "Animation Associate - 3D", defaultDurationHours: 310 },
    { courseName: "Animator", defaultDurationHours: 610 },
    { courseName: "Camera Operator", defaultDurationHours: 490 },
    { courseName: "Costume Designer", defaultDurationHours: 730 },
    { courseName: "Digital Marketing Manager", defaultDurationHours: 910 },
    { courseName: "Fine-Arts Teacher", defaultDurationHours: 1000 },
    { courseName: "Game Artist", defaultDurationHours: 1000 },
    { courseName: "Graphic Designer", defaultDurationHours: 580 },
    { courseName: "Live Performer - Folk Art (Dancer / Singer)", defaultDurationHours: 400 },
    { courseName: "Make-Up Artist", defaultDurationHours: 490 },
    { courseName: "Music Composer/Director", defaultDurationHours: 940 },
    { courseName: "Voice-Over Artist", defaultDurationHours: 550 },
  ],
  "Mining": [
    { courseName: "Driver Special Utility Vehicle", defaultDurationHours: 940 },
    { courseName: "Mine Shotfirer/Blaster", defaultDurationHours: 880 },
    { courseName: "Rig-Mounted Drill Operator", defaultDurationHours: 610 },
  ],
  "Plumbing": [
    { courseName: "Drinking Water Purifier Technician", defaultDurationHours: 100 },
    { courseName: "Plumber - General", defaultDurationHours: 532 },
  ],
  "Power": [
    { courseName: "Assistant Technician - Street Light Installation & Maintenance", defaultDurationHours: 400 },
    { courseName: "Industrial Electrician", defaultDurationHours: 640 },
    { courseName: "Jr. Technician (Smart Energy Meter)", defaultDurationHours: 520 },
    { courseName: "Junior Engineer- Power Distribution", defaultDurationHours: 670 },
    { courseName: "Rooftop Solar PV (Installation & Maintenance)", defaultDurationHours: 160 },
  ],
  "PwD": [
    { courseName: "Assistant Sewing Machine Operator (Divyangjan)- ID", defaultDurationHours: 880 },
    { courseName: "Data Entry Operator (Divyangjan)- ID", defaultDurationHours: 1120 },
    { courseName: "Data Entry Operator (Divyangjan)- MD", defaultDurationHours: 1120 },
    { courseName: "Food & Beverage Service Associate (Divyangjan)", defaultDurationHours: 790 },
    { courseName: "Indian Sign Language", defaultDurationHours: 440 },
  ],
  "Retail": [
    { courseName: "Digital Cataloguer", defaultDurationHours: 580 },
    { courseName: "Direct Seller", defaultDurationHours: 550 },
    { courseName: "Marketing Manager (E- commerce)", defaultDurationHours: 730 },
    { courseName: "Retail Sales Assistant", defaultDurationHours: 490 },
    { courseName: "Retail Sales Associate", defaultDurationHours: 460 },
    { courseName: "Retail Store Ops Assistant", defaultDurationHours: 300 },
    { courseName: "Visual Merchandiser", defaultDurationHours: 640 },
  ],
  "Rubber": [
    { courseName: "Assistant Operator - Material Handling and Storage", defaultDurationHours: 430 },
    { courseName: "Assistant Operator -Tyre Balancing", defaultDurationHours: 490 },
    { courseName: "Designer - Die and Mould for Plastic", defaultDurationHours: 580 },
    { courseName: "Designer - Plastic Product including toys", defaultDurationHours: 580 },
    { courseName: "Jr. Machine Operator - CNC Turning of Plastic (Lathe)", defaultDurationHours: 430 },
    { courseName: "Operator-Plastic 3D printing", defaultDurationHours: 610 },
    { courseName: "Rubber Moulding and Curing Supervisor", defaultDurationHours: 700 },
    { courseName: "Rubber Technician", defaultDurationHours: 550 },
    { courseName: "Technician - TQC for Plastic Materials & Products", defaultDurationHours: 550 },
  ],
  "Sports": [
    { courseName: "Lifeguard-Pool", defaultDurationHours: 520 },
    { courseName: "Self-Defense Trainer", defaultDurationHours: 520 },
    { courseName: "Sports Nutritionist", defaultDurationHours: 760 },
    { courseName: "Swimming Instructor", defaultDurationHours: 820 },
  ],
  "Telecom": [
    { courseName: "5G System Integrator", defaultDurationHours: 670 },
    { courseName: "Broadband Technician", defaultDurationHours: 610 },
    { courseName: "Call Center Executive", defaultDurationHours: 490 },
    { courseName: "Cloud Computing - Jr. Analyst", defaultDurationHours: 610 },
    { courseName: "Drone Data Processor", defaultDurationHours: 640 },
    { courseName: "Drone Monitoring and Maintenance Associate", defaultDurationHours: 520 },
    { courseName: "In-Store Promoter", defaultDurationHours: 490 },
    { courseName: "Information Network Cabling", defaultDurationHours: 610 },
    { courseName: "Information and Communication Technology (ICT) Engineer - 5G Networks", defaultDurationHours: 700 },
    { courseName: "IoT Technical Service Operator", defaultDurationHours: 490 },
    { courseName: "Machine Learning (ML) Engineer", defaultDurationHours: 730 },
    { courseName: "Telecom Customer Care Executive - Call Center/Relationship Center", defaultDurationHours: 640 },
    { courseName: "Telecom Customer Care Executive - Repair Center", defaultDurationHours: 490 },
    { courseName: "Telecom Technician - IoT Devices/Systems", defaultDurationHours: 640 },
  ],
  "Textile": [
    { courseName: "Assistant Design Maker - Textiles", defaultDurationHours: 460 },
    { courseName: "Textile Dyeing Machine Operator", defaultDurationHours: 370 },
    { courseName: "Textile Printing Machine Operator", defaultDurationHours: 520 },
  ],
  "Tourism & Hospitality": [
    { courseName: "Customer Service Representative (Meet and Greet)", defaultDurationHours: 610 },
    { courseName: "Duty Manager", defaultDurationHours: 670 },
    { courseName: "Food & Beverage Service - Associate", defaultDurationHours: 520 },
    { courseName: "Food Delivery Associate", defaultDurationHours: 370 },
    { courseName: "Front Office Assistant", defaultDurationHours: 400 },
    { courseName: "Front Office Manager", defaultDurationHours: 940 },
    { courseName: "Guest House Caretaker", defaultDurationHours: 580 },
    { courseName: "Guest Service Executive (Front Office)", defaultDurationHours: 640 },
    { courseName: "Kitchen Steward", defaultDurationHours: 340 },
    { courseName: "Street Food Vendor- Standalone", defaultDurationHours: 550 },
    { courseName: "Tour Guide", defaultDurationHours: 760 },
    { courseName: "Transport Coordinator- Tourism and Hospitality", defaultDurationHours: 550 },
    { courseName: "Travel Consultant", defaultDurationHours: 948 },
  ],
};

/**
 * Helper to retrieve courses for a given sector.
 * If sector is not matched or empty, returns all courses or fallback.
 */
export function getCoursesForSector(sector?: string): SectorCourseItem[] {
  if (!sector) {
    // Return all courses across all sectors
    const allCourses: SectorCourseItem[] = [];
    const seen = new Set<string>();
    Object.values(SECTOR_COURSES_MAP).forEach(list => {
      list.forEach(c => {
        if (!seen.has(c.courseName)) {
          seen.add(c.courseName);
          allCourses.push(c);
        }
      });
    });
    return allCourses;
  }

  // Exact or case-insensitive / normalized match
  const normalizedSector = sector.trim().toLowerCase();
  for (const [key, courses] of Object.entries(SECTOR_COURSES_MAP)) {
    if (key.toLowerCase() === normalizedSector) {
      return courses;
    }
  }

  // Fallback if partial match
  for (const [key, courses] of Object.entries(SECTOR_COURSES_MAP)) {
    if (key.toLowerCase().includes(normalizedSector) || normalizedSector.includes(key.toLowerCase())) {
      return courses;
    }
  }

  return [];
}
